version: '3'
services:
  streaming-html:
    build:
      context: .
      dockerfile: Dockerfile
    image: ravikishans/htmlfile:latest
    environment:
      - IP = localhost
    ports:
      - 80:80   

